ERROR - 2023-01-15 12:05:03 --> Error connecting to the database: mysqli_sql_exception: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ja_zerei\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\ja_zerei\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'ja_zerei', 3306, '', 0)
#1 C:\xampp\htdocs\ja_zerei\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ja_zerei\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ja_zerei\system\Database\BaseConnection.php(1361): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\ja_zerei\system\Database\BaseConnection.php(1380): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\ja_zerei\system\Database\MigrationRunner.php(760): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 C:\xampp\htdocs\ja_zerei\system\Database\MigrationRunner.php(168): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 C:\xampp\htdocs\ja_zerei\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 C:\xampp\htdocs\ja_zerei\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 C:\xampp\htdocs\ja_zerei\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 C:\xampp\htdocs\ja_zerei\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#11 C:\xampp\htdocs\ja_zerei\system\CodeIgniter.php(918): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#12 C:\xampp\htdocs\ja_zerei\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#13 C:\xampp\htdocs\ja_zerei\system\CodeIgniter.php(345): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\ja_zerei\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\ja_zerei\spark(98): CodeIgniter\CLI\Console->run()
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente in C:\xampp\htdocs\ja_zerei\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\ja_zerei\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ja_zerei\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ja_zerei\system\Database\BaseConnection.php(1361): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\ja_zerei\system\Database\BaseConnection.php(1380): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\ja_zerei\system\Database\MigrationRunner.php(760): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 C:\xampp\htdocs\ja_zerei\system\Database\MigrationRunner.php(168): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 C:\xampp\htdocs\ja_zerei\system\Commands\Database\Migrate.php(84): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 C:\xampp\htdocs\ja_zerei\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 C:\xampp\htdocs\ja_zerei\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 C:\xampp\htdocs\ja_zerei\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#10 C:\xampp\htdocs\ja_zerei\system\CodeIgniter.php(918): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#11 C:\xampp\htdocs\ja_zerei\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#12 C:\xampp\htdocs\ja_zerei\system\CodeIgniter.php(345): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\ja_zerei\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\ja_zerei\spark(98): CodeIgniter\CLI\Console->run()
#15 {main}
ERROR - 2023-01-15 12:20:22 --> mysqli_sql_exception: Table 'ja_zerei.users' doesn't exist in C:\xampp\htdocs\ja_zerei\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\ja_zerei\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\ja_zerei\system\Database\BaseConnection.php(666): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\ja_zerei\system\Database\BaseConnection.php(593): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\ja_zerei\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\ja_zerei\app\Database\Seeds\UsersAdmSeeds.php(11): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\ja_zerei\system\Database\Seeder.php(146): App\Database\Seeds\UsersAdmSeeds->run()
#6 C:\xampp\htdocs\ja_zerei\system\Commands\Database\Seed.php(77): CodeIgniter\Database\Seeder->call('App\\Database\\Se...')
#7 C:\xampp\htdocs\ja_zerei\system\CLI\Commands.php(63): CodeIgniter\Commands\Database\Seed->run(Array)
#8 C:\xampp\htdocs\ja_zerei\system\CLI\CommandRunner.php(65): CodeIgniter\CLI\Commands->run('db:seed', Array)
#9 C:\xampp\htdocs\ja_zerei\system\CLI\CommandRunner.php(51): CodeIgniter\CLI\CommandRunner->index(Array)
#10 C:\xampp\htdocs\ja_zerei\system\CodeIgniter.php(918): CodeIgniter\CLI\CommandRunner->_remap('index', Array)
#11 C:\xampp\htdocs\ja_zerei\system\CodeIgniter.php(480): CodeIgniter\CodeIgniter->runController(Object(CodeIgniter\CLI\CommandRunner))
#12 C:\xampp\htdocs\ja_zerei\system\CodeIgniter.php(345): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\ja_zerei\system\CLI\Console.php(48): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\ja_zerei\spark(98): CodeIgniter\CLI\Console->run()
#15 {main}
CRITICAL - 2023-01-15 17:18:44 --> Class "Config\App\Filters\Auth" not found
in SYSTEMPATH\Filters\Filters.php on line 166.
 1 SYSTEMPATH\CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 2 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-15 17:19:41 --> Class "Config\App\Auth" not found
in SYSTEMPATH\Filters\Filters.php on line 166.
 1 SYSTEMPATH\CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 2 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-15 17:20:01 --> Class "Config\Auth" not found
in SYSTEMPATH\Filters\Filters.php on line 166.
 1 SYSTEMPATH\CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 2 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-15 17:20:41 --> Class "Config\App\Filters\Auth" not found
in SYSTEMPATH\Filters\Filters.php on line 166.
 1 SYSTEMPATH\CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 2 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-15 17:22:10 --> Class "Config\App\Filters\Auth" not found
in SYSTEMPATH\Filters\Filters.php on line 166.
 1 SYSTEMPATH\CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 2 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-15 17:23:01 --> Class "Config\App\Filters\Auth" not found
in SYSTEMPATH\Filters\Filters.php on line 166.
 1 SYSTEMPATH\CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 2 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-15 17:23:45 --> auth filter must have a matching alias defined.
in SYSTEMPATH\Filters\Filters.php on line 340.
 1 SYSTEMPATH\Filters\Filters.php(340): CodeIgniter\Filters\Exceptions\FilterException::forNoAlias('auth')
 2 SYSTEMPATH\CodeIgniter.php(444): CodeIgniter\Filters\Filters->enableFilter('auth', 'before')
 3 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-01-15 17:24:05 --> Class "Config\App\Filters\Auth" not found
in SYSTEMPATH\Filters\Filters.php on line 166.
 1 SYSTEMPATH\CodeIgniter.php(453): CodeIgniter\Filters\Filters->run('C:\\', 'before')
 2 SYSTEMPATH\CodeIgniter.php(349): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 3 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
